In [ ]:
import pandas as pd
import numpy as np
import mysql.connector

In [ ]:
#-------------------------------------------
# step 1 : Load datasets
#-------------------------------------------

In [ ]:
customers = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\customers.csv")
accounts = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\accounts.csv")
transactions = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\transactions.csv")
loans = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\loans.csv")
credit_cards = pd.read_json(r"C:\Users\aarth\OneDrive\Documents\project\credit_cards.json")
branches = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\branches.csv")
support_tickets = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\support_tickets.csv")

In [ ]:
#-------------------------------------------
# step 2 : Data cleaning
#-------------------------------------------

##### customers

In [ ]:
customers.head()

,customer_id,name,gender,age,city,account_type,join_date
0,C0001,Richard Wilson,M,65,Kimberlyburgh,Savings,2023-08-27
1,C0002,Holly Parker,F,41,Port David,Current,2023-12-08
2,C0003,Megan Alvarez,M,46,West Laurieton,Savings,2022-05-25
3,C0004,Nicholas Stewart,F,39,Amyville,Current,2020-11-30
4,C0005,Douglas Anderson,M,70,New Craigport,Current,2023-01-29

In [ ]:
customers.isnull().sum()

customer_id     0
name            0
gender          0
age             0
city            0
account_type    0
join_date       0
dtype: int64

In [ ]:
customers.duplicated().sum()

np.int64(0)

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   500 non-null    object
 1   name          500 non-null    object
 2   gender        500 non-null    object
 3   age           500 non-null    int64
 4   city          500 non-null    object
 5   account_type  500 non-null    object
 6   join_date     500 non-null    object
dtypes: int64(1), object(6)
memory usage: 27.5+ KB

In [ ]:
customers['join_date'] = pd.to_datetime(customers['join_date'])

##### accounts

In [ ]:
accounts.head()

  customer_id  account_balance         last_updated
0       C0001        293729.87  2025-05-24 09:46:29
1       C0002        150735.15  2025-05-24 09:46:29
2       C0003        170156.21  2025-05-24 09:46:29
3       C0004        311383.96  2025-05-24 09:46:29
4       C0005         60320.75  2025-05-24 09:46:29

In [ ]:
accounts.isnull().sum()

customer_id        0
account_balance    0
last_updated       0
dtype: int64

In [ ]:
accounts.duplicated().sum()

np.int64(0)

In [ ]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      500 non-null    object
 1   account_balance  500 non-null    float64
 2   last_updated     500 non-null    object
dtypes: float64(1), object(2)
memory usage: 11.8+ KB

In [ ]:
accounts['last_updated'] = pd.to_datetime(accounts['last_updated'])

In [ ]:
print(accounts.dtypes)

customer_id                object
account_balance           float64
last_updated       datetime64[ns]
dtype: object

##### Transactions

In [ ]:
transactions.head()

   txn_id customer_id    txn_type    amount             txn_time   status
0  T00001       C0363     deposit  44442.71  2025-02-14 06:26:00  success
1  T00002       C0432     deposit  15737.59  2025-03-27 07:21:21  success
2  T00003       C0084  withdrawal  82150.70  2024-07-31 18:28:06  success
3  T00004       C0067  withdrawal  20313.86  2024-11-11 12:18:47  success
4  T00005       C0485  withdrawal  74536.08  2025-04-15 10:52:59  success

In [ ]:
transactions.isnull().sum()

txn_id         0
customer_id    0
txn_type       0
amount         0
txn_time       0
status         0
dtype: int64

In [ ]:
transactions.duplicated().sum()

np.int64(0)

In [ ]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   txn_id       10000 non-null  object
 1   customer_id  10000 non-null  object
 2   txn_type     10000 non-null  object
 3   amount       10000 non-null  float64
 4   txn_time     10000 non-null  object
 5   status       10000 non-null  object
dtypes: float64(1), object(5)
memory usage: 468.9+ KB

In [ ]:
transactions['txn_time'] = pd.to_datetime(transactions['txn_time'])

In [ ]:
print(transactions.dtypes)

txn_id                 object
customer_id            object
txn_type               object
amount                float64
txn_time       datetime64[ns]
status                 object
dtype: object

##### Loans

In [ ]:
loans.head()

,Loan_ID,Customer_ID,Account_ID,Branch,Loan_Type,Loan_Amount,Interest_Rate,Loan_Term_Months,Start_Date,End_Date,Loan_Status
0,1,1559,2090,Perez Ltd Branch,Personal,259805,12.43,60,2017-07-03,2022-06-07,Active
1,2,1028,2575,Harris-Marshall Branch,Business,3589336,6.75,24,2017-06-14,2019-06-04,Active
2,3,1164,2433,"Taylor, David and Brown Branch",Auto,4621300,9.86,240,2021-08-10,2041-04-27,Closed
3,4,1100,2368,Robertson and Sons Branch,Home,2380953,7.74,120,2016-02-23,2026-01-01,Approved
4,5,1081,2566,"Parrish, Hall and Adams Branch",Home,2268961,12.96,240,2021-01-05,2040-09-22,Approved

In [ ]:
loans.isnull().sum()

Loan_ID             0
Customer_ID         0
Account_ID          0
Branch              0
Loan_Type           0
Loan_Amount         0
Interest_Rate       0
Loan_Term_Months    0
Start_Date          0
End_Date            0
Loan_Status         0
dtype: int64

In [ ]:
loans.duplicated().sum()

np.int64(0)

In [ ]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553 entries, 0 to 552
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Loan_ID           553 non-null    int64
 1   Customer_ID       553 non-null    int64
 2   Account_ID        553 non-null    int64
 3   Branch            553 non-null    object
 4   Loan_Type         553 non-null    object
 5   Loan_Amount       553 non-null    int64
 6   Interest_Rate     553 non-null    float64
 7   Loan_Term_Months  553 non-null    int64
 8   Start_Date        553 non-null    object
 9   End_Date          553 non-null    object
 10  Loan_Status       553 non-null    object
dtypes: float64(1), int64(5), object(5)
memory usage: 47.6+ KB

In [ ]:
loans['Customer_ID'] = loans['Customer_ID'].astype(str)

In [ ]:
loans['Start_Date'] = pd.to_datetime(loans['Start_Date'])

In [ ]:
loans['End_Date'] = pd.to_datetime(loans['End_Date'])

In [ ]:
print(loans.dtypes)

Loan_ID                      int64
Customer_ID                 object
Account_ID                   int64
Branch                      object
Loan_Type                   object
Loan_Amount                  int64
Interest_Rate              float64
Loan_Term_Months             int64
Start_Date          datetime64[ns]
End_Date            datetime64[ns]
Loan_Status                 object
dtype: object

##### credit cards dataset

In [ ]:
credit_cards.head()

,Card_ID,Customer_ID,Account_ID,Branch,Card_Number,Card_Type,Card_Network,Credit_Limit,Current_Balance,Issued_Date,Expiry_Date,Status
0,1,1559,2090,Perez Ltd Branch,4960013389083863,Business,Visa,178393,39819.23,2015-04-13,2019-10-27,Expired
1,2,1160,2221,Miller Inc Branch,6511615594078161,Platinum,RuPay,416026,175818.58,2015-01-27,2018-12-18,Expired
2,3,1297,2082,"Miles, Patterson and Murray Branch",6316475255341928,Gold,RuPay,419398,29171.29,2021-06-22,2025-07-19,Active
3,4,1333,2058,"Shepard, Gonzales and Cooper Branch",3305641395376724,Gold,Amex,385544,265316.71,2019-04-04,2023-10-07,Active
4,5,1371,2225,Wilson PLC Branch,6287101226916697,Platinum,RuPay,274622,246561.92,2023-05-18,2029-08-26,Expired

In [ ]:
credit_cards.isnull().sum()

Card_ID            0
Customer_ID        0
Account_ID         0
Branch             0
Card_Number        0
Card_Type          0
Card_Network       0
Credit_Limit       0
Current_Balance    0
Issued_Date        0
Expiry_Date        0
Status             0
dtype: int64

In [ ]:
credit_cards.duplicated().sum()

np.int64(0)

In [ ]:
credit_cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Card_ID          557 non-null    int64
 1   Customer_ID      557 non-null    int64
 2   Account_ID       557 non-null    int64
 3   Branch           557 non-null    object
 4   Card_Number      557 non-null    int64
 5   Card_Type        557 non-null    object
 6   Card_Network     557 non-null    object
 7   Credit_Limit     557 non-null    int64
 8   Current_Balance  557 non-null    float64
 9   Issued_Date      557 non-null    object
 10  Expiry_Date      557 non-null    object
 11  Status           557 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 52.3+ KB

In [ ]:
credit_cards['Customer_ID'] = credit_cards['Customer_ID'].astype(str)

In [ ]:
credit_cards['Card_Number'] = credit_cards['Card_Number'].astype(str)

In [ ]:
credit_cards['Issued_Date'] = pd.to_datetime(credit_cards['Issued_Date'])

In [ ]:
credit_cards['Expiry_Date'] = pd.to_datetime(credit_cards['Expiry_Date'])

In [ ]:
print(credit_cards.dtypes)

Card_ID                     int64
Customer_ID                object
Account_ID                  int64
Branch                     object
Card_Number                object
Card_Type                  object
Card_Network               object
Credit_Limit                int64
Current_Balance           float64
Issued_Date        datetime64[ns]
Expiry_Date        datetime64[ns]
Status                     object
dtype: object

##### Branches

In [ ]:
branches.head()

,Branch_ID,Branch_Name,City,Manager_Name,Total_Employees,Branch_Revenue,Opening_Date,Performance_Rating
0,1,"Wang, Mcdonald and Church Branch",Kellitown,Kevin Jones,141,16849288.09,2008-08-01,2
1,2,Crawford-Torres Branch,Angelaburgh,Andrea Steele,39,5822279.32,2015-09-17,1
2,3,Bridges Inc Branch,Johnsonfort,Michael Coleman,195,2114594.03,2012-07-30,3
3,4,Garcia Group Branch,New Kyleberg,Dawn Cooper,144,3390389.63,2018-06-27,2
4,5,"Arroyo, Moore and Freeman Branch",West Coryborough,Samantha Kennedy,42,2771910.11,2012-01-04,5

In [ ]:
branches.isnull().sum()

Branch_ID             0
Branch_Name           0
City                  0
Manager_Name          0
Total_Employees       0
Branch_Revenue        0
Opening_Date          0
Performance_Rating    0
dtype: int64

In [ ]:
branches.duplicated().sum()

np.int64(0)

In [ ]:
branches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Branch_ID           520 non-null    int64
 1   Branch_Name         520 non-null    object
 2   City                520 non-null    object
 3   Manager_Name        520 non-null    object
 4   Total_Employees     520 non-null    int64
 5   Branch_Revenue      520 non-null    float64
 6   Opening_Date        520 non-null    object
 7   Performance_Rating  520 non-null    int64
dtypes: float64(1), int64(3), object(4)
memory usage: 32.6+ KB

In [ ]:
branches['Opening_Date'] = pd.to_datetime(branches['Opening_Date'])

In [ ]:
print(branches.dtypes)

Branch_ID                      int64
Branch_Name                   object
City                          object
Manager_Name                  object
Total_Employees                int64
Branch_Revenue               float64
Opening_Date          datetime64[ns]
Performance_Rating             int64
dtype: object

##### Support_Tickets

In [ ]:
support_tickets.head()

,Ticket_ID,Customer_ID,Account_ID,Loan_ID,Branch_Name,Issue_Category,Description,Date_Opened,Date_Closed,Priority,Status,Resolution_Remarks,Support_Agent,Channel,Customer_Rating
0,T00001,C0478,A1825,NaN,Gonzalez-Martin Branch,Loan Payment Delay,Client raised loan payment delay.,2017-09-30,2017-10-24,Low,Closed,Card replaced and activated.,Leena Apte,Email,1
1,T00002,C0443,A3583,NaN,Baldwin and Sons Branch,Loan Foreclosure,Client raised loan foreclosure.,2015-04-19,2015-05-12,Critical,In Progress,Card replaced and activated.,Owen Mahajan,In-person,1
2,T00003,C0057,A2616,442.0,"Porter, Osborne and Mendez Branch",Interest Rate Dispute,Customer reported interest rate dispute.,2016-09-28,2016-10-23,High,Resolved,Loan schedule updated.,Wishi Chhabra,Email,4
3,T00004,C0301,A8786,NaN,"Stafford, Oneal and Williams Branch",Mismatch in Account Statement,Client raised mismatch in account statement.,2019-03-31,2019-04-10,High,Closed,Pending customer verification.,Gabriel Mutti,Email,1
4,T00005,C0238,A3734,NaN,Evans-Mercado Branch,KYC Update Required,System detected kyc update required.,2017-08-11,NaN,Critical,Resolved,Pending customer verification.,Ekani Oza,In-person,2

In [ ]:
support_tickets.duplicated().sum()

np.int64(0)

In [ ]:
support_tickets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ticket_ID           600 non-null    object
 1   Customer_ID         600 non-null    object
 2   Account_ID          600 non-null    object
 3   Loan_ID             229 non-null    float64
 4   Branch_Name         600 non-null    object
 5   Issue_Category      600 non-null    object
 6   Description         600 non-null    object
 7   Date_Opened         600 non-null    object
 8   Date_Closed         496 non-null    object
 9   Priority            600 non-null    object
 10  Status              600 non-null    object
 11  Resolution_Remarks  600 non-null    object
 12  Support_Agent       600 non-null    object
 13  Channel             600 non-null    object
 14  Customer_Rating     600 non-null    int64
dtypes: float64(1), int64(1), object(13)
memory usage: 70.4+ KB

In [1]:
support_tickets['Loan_ID'] = support_tickets['Loan_ID'].astype(str)

NameError: name 'support_tickets' is not defined

In [ ]:
support_tickets['Date_Opened'] = pd.to_datetime(support_tickets['Date_Opened'])

In [ ]:
support_tickets['Date_Closed'] = pd.to_datetime(support_tickets['Date_Closed'])

In [ ]:
support_tickets.isnull().sum()

Ticket_ID               0
Customer_ID             0
Account_ID              0
Loan_ID                 0
Branch_Name             0
Issue_Category          0
Description             0
Date_Opened             0
Date_Closed           104
Priority                0
Status                  0
Resolution_Remarks      0
Support_Agent           0
Channel                 0
Customer_Rating         0
dtype: int64

In [ ]:
support_tickets['Loan_ID'] = support_tickets['Loan_ID'].replace(
    ['nan', 'NaN', 'None', ''], np.nan
)

In [ ]:
support_tickets['Date_Closed'] = pd.to_datetime(
    support_tickets['Date_Closed'], errors='coerce'
)

In [ ]:
#-------------------------------------------
# step 3 : connect to mysql
#-------------------------------------------

In [ ]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Aarthiba@123"
)
cursor = conn.cursor()

#### create database

In [ ]:
cursor.execute("CREATE DATABASE IF NOT EXISTS banksight")
cursor.execute("USE banksight")
print("Database selected")

Database selected

In [ ]:
#-------------------------------------------
# step 4 : create tables
#-------------------------------------------

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS customers (
    customer_id VARCHAR(10) PRIMARY KEY,
    name VARCHAR(50),
    gender CHAR(1),
    age INT,
    city VARCHAR(50),
    account_type VARCHAR(20),
    join_date DATE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS accounts (
    customer_id VARCHAR(10),
    account_balance DECIMAL(12,2),
    last_updated DATETIME,
               
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
    ON DELETE CASCADE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS transactions (
    txn_id VARCHAR(10) PRIMARY KEY,
    customer_id VARCHAR(10),
    txn_type VARCHAR(50),
    amount DECIMAL(12,2),
    txn_time DATETIME,
    status VARCHAR(50),
               
    FOREIGN KEY (customer_id) 
    REFERENCES customers(customer_id)
    ON DELETE CASCADE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS loans (
    loan_id INT PRIMARY KEY,
    customer_id VARCHAR(10),
    account_id INT,
    branch VARCHAR(50),
    loan_type VARCHAR(50),
    loan_amount INT,
    interest_rate DECIMAL(12,2),
    loan_term_months INT,
    start_date DATE,
    end_date DATE,
    loan_status VARCHAR(50),
               
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
    ON DELETE CASCADE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS credit_cards (
    card_id INT PRIMARY KEY,
    customer_id VARCHAR(10),
    account_id INT,
    branch VARCHAR(50),
    card_number VARCHAR(20),
    card_type VARCHAR(50),
    card_network VARCHAR(50),
    credit_limit INT,
    current_balance DECIMAL(12,2),
    issued_date DATE,
    expiry_date DATE,
    status VARCHAR(50),
               
    FOREIGN KEY (customer_id) 
    REFERENCES customers( customer_id)
    ON DELETE CASCADE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS branches (
    branch_id INT PRIMARY KEY,
    branch_name VARCHAR(50),
    city VARCHAR(50),
    manager_name VARCHAR(50),
    total_employees int,
    branch_revenue DECIMAL(12,2),
    opening_date DATE,
    performance_rating int
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS support_tickets (
    ticket_id VARCHAR(10) PRIMARY KEY,
    customer_id VARCHAR(10),
    account_id VARCHAR(10),
    loan_id VARCHAR(50) NULL,
    branch_name VARCHAR(50),
    issue_category VARCHAR(50),
    description  TEXT,
    date_opened DATE,
    date_closed DATE,
    priority VARCHAR(50),
    status VARCHAR(50),
    resolution_remarks TEXT,
    support_agent VARCHAR(50),
    channel VARCHAR(50),
    customer_rating int,
               
    FOREIGN KEY (customer_id) 
    REFERENCES customers(customer_id)
    ON DELETE CASCADE
)
""")

#### insert rows

In [ ]:
for _, row in customers.iterrows():
    cursor.execute("""
        INSERT INTO customers (customer_id, name, gender, age, city, account_type, join_date)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON DUPLICATE KEY UPDATE
            name = VALUES(name),
            gender = VALUES(gender),
            age = VALUES(age),
            city = VALUES(city),
            account_type = VALUES(account_type),
            join_date = VALUES(join_date)
    """, (
        row['customer_id'], 
        row['name'], 
        row['gender'], 
        row['age'], 
        row['city'], 
        row['account_type'], 
        row['join_date']
    ))

conn.commit()

In [ ]:
import pandas as pd
import numpy as np
import mysql.connector

In [ ]:
#-------------------------------------------
# step 1 : Load datasets
#-------------------------------------------

In [ ]:
customers = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\customers.csv")
accounts = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\accounts.csv")
transactions = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\transactions.csv")
loans = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\loans.csv")
credit_cards = pd.read_json(r"C:\Users\aarth\OneDrive\Documents\project\credit_cards.json")
branches = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\branches.csv")
support_tickets = pd.read_csv(r"C:\Users\aarth\OneDrive\Documents\project\support_tickets.csv")

In [ ]:
#-------------------------------------------
# step 2 : Data cleaning
#-------------------------------------------

##### customers

In [ ]:
customers.head()

,customer_id,name,gender,age,city,account_type,join_date
0,C0001,Richard Wilson,M,65,Kimberlyburgh,Savings,2023-08-27
1,C0002,Holly Parker,F,41,Port David,Current,2023-12-08
2,C0003,Megan Alvarez,M,46,West Laurieton,Savings,2022-05-25
3,C0004,Nicholas Stewart,F,39,Amyville,Current,2020-11-30
4,C0005,Douglas Anderson,M,70,New Craigport,Current,2023-01-29

In [ ]:
customers.isnull().sum()

customer_id     0
name            0
gender          0
age             0
city            0
account_type    0
join_date       0
dtype: int64

In [ ]:
customers.duplicated().sum()

np.int64(0)

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   500 non-null    object
 1   name          500 non-null    object
 2   gender        500 non-null    object
 3   age           500 non-null    int64
 4   city          500 non-null    object
 5   account_type  500 non-null    object
 6   join_date     500 non-null    object
dtypes: int64(1), object(6)
memory usage: 27.5+ KB

In [ ]:
customers['join_date'] = pd.to_datetime(customers['join_date'])

##### accounts

In [ ]:
accounts.head()

  customer_id  account_balance         last_updated
0       C0001        293729.87  2025-05-24 09:46:29
1       C0002        150735.15  2025-05-24 09:46:29
2       C0003        170156.21  2025-05-24 09:46:29
3       C0004        311383.96  2025-05-24 09:46:29
4       C0005         60320.75  2025-05-24 09:46:29

In [ ]:
accounts.isnull().sum()

customer_id        0
account_balance    0
last_updated       0
dtype: int64

In [ ]:
accounts.duplicated().sum()

np.int64(0)

In [ ]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      500 non-null    object
 1   account_balance  500 non-null    float64
 2   last_updated     500 non-null    object
dtypes: float64(1), object(2)
memory usage: 11.8+ KB

In [ ]:
accounts['last_updated'] = pd.to_datetime(accounts['last_updated'])

In [ ]:
print(accounts.dtypes)

customer_id                object
account_balance           float64
last_updated       datetime64[ns]
dtype: object

##### Transactions

In [ ]:
transactions.head()

   txn_id customer_id    txn_type    amount             txn_time   status
0  T00001       C0363     deposit  44442.71  2025-02-14 06:26:00  success
1  T00002       C0432     deposit  15737.59  2025-03-27 07:21:21  success
2  T00003       C0084  withdrawal  82150.70  2024-07-31 18:28:06  success
3  T00004       C0067  withdrawal  20313.86  2024-11-11 12:18:47  success
4  T00005       C0485  withdrawal  74536.08  2025-04-15 10:52:59  success

In [ ]:
transactions.isnull().sum()

txn_id         0
customer_id    0
txn_type       0
amount         0
txn_time       0
status         0
dtype: int64

In [ ]:
transactions.duplicated().sum()

np.int64(0)

In [ ]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   txn_id       10000 non-null  object
 1   customer_id  10000 non-null  object
 2   txn_type     10000 non-null  object
 3   amount       10000 non-null  float64
 4   txn_time     10000 non-null  object
 5   status       10000 non-null  object
dtypes: float64(1), object(5)
memory usage: 468.9+ KB

In [ ]:
transactions['txn_time'] = pd.to_datetime(transactions['txn_time'])

In [ ]:
print(transactions.dtypes)

txn_id                 object
customer_id            object
txn_type               object
amount                float64
txn_time       datetime64[ns]
status                 object
dtype: object

##### Loans

In [ ]:
loans.head()

,Loan_ID,Customer_ID,Account_ID,Branch,Loan_Type,Loan_Amount,Interest_Rate,Loan_Term_Months,Start_Date,End_Date,Loan_Status
0,1,1559,2090,Perez Ltd Branch,Personal,259805,12.43,60,2017-07-03,2022-06-07,Active
1,2,1028,2575,Harris-Marshall Branch,Business,3589336,6.75,24,2017-06-14,2019-06-04,Active
2,3,1164,2433,"Taylor, David and Brown Branch",Auto,4621300,9.86,240,2021-08-10,2041-04-27,Closed
3,4,1100,2368,Robertson and Sons Branch,Home,2380953,7.74,120,2016-02-23,2026-01-01,Approved
4,5,1081,2566,"Parrish, Hall and Adams Branch",Home,2268961,12.96,240,2021-01-05,2040-09-22,Approved

In [ ]:
loans.isnull().sum()

Loan_ID             0
Customer_ID         0
Account_ID          0
Branch              0
Loan_Type           0
Loan_Amount         0
Interest_Rate       0
Loan_Term_Months    0
Start_Date          0
End_Date            0
Loan_Status         0
dtype: int64

In [ ]:
loans.duplicated().sum()

np.int64(0)

In [ ]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553 entries, 0 to 552
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Loan_ID           553 non-null    int64
 1   Customer_ID       553 non-null    int64
 2   Account_ID        553 non-null    int64
 3   Branch            553 non-null    object
 4   Loan_Type         553 non-null    object
 5   Loan_Amount       553 non-null    int64
 6   Interest_Rate     553 non-null    float64
 7   Loan_Term_Months  553 non-null    int64
 8   Start_Date        553 non-null    object
 9   End_Date          553 non-null    object
 10  Loan_Status       553 non-null    object
dtypes: float64(1), int64(5), object(5)
memory usage: 47.6+ KB

In [ ]:
loans['Customer_ID'] = loans['Customer_ID'].astype(str)

In [ ]:
loans['Start_Date'] = pd.to_datetime(loans['Start_Date'])

In [ ]:
loans['End_Date'] = pd.to_datetime(loans['End_Date'])

In [ ]:
print(loans.dtypes)

Loan_ID                      int64
Customer_ID                 object
Account_ID                   int64
Branch                      object
Loan_Type                   object
Loan_Amount                  int64
Interest_Rate              float64
Loan_Term_Months             int64
Start_Date          datetime64[ns]
End_Date            datetime64[ns]
Loan_Status                 object
dtype: object

##### credit cards dataset

In [ ]:
credit_cards.head()

,Card_ID,Customer_ID,Account_ID,Branch,Card_Number,Card_Type,Card_Network,Credit_Limit,Current_Balance,Issued_Date,Expiry_Date,Status
0,1,1559,2090,Perez Ltd Branch,4960013389083863,Business,Visa,178393,39819.23,2015-04-13,2019-10-27,Expired
1,2,1160,2221,Miller Inc Branch,6511615594078161,Platinum,RuPay,416026,175818.58,2015-01-27,2018-12-18,Expired
2,3,1297,2082,"Miles, Patterson and Murray Branch",6316475255341928,Gold,RuPay,419398,29171.29,2021-06-22,2025-07-19,Active
3,4,1333,2058,"Shepard, Gonzales and Cooper Branch",3305641395376724,Gold,Amex,385544,265316.71,2019-04-04,2023-10-07,Active
4,5,1371,2225,Wilson PLC Branch,6287101226916697,Platinum,RuPay,274622,246561.92,2023-05-18,2029-08-26,Expired

In [ ]:
credit_cards.isnull().sum()

Card_ID            0
Customer_ID        0
Account_ID         0
Branch             0
Card_Number        0
Card_Type          0
Card_Network       0
Credit_Limit       0
Current_Balance    0
Issued_Date        0
Expiry_Date        0
Status             0
dtype: int64

In [ ]:
credit_cards.duplicated().sum()

np.int64(0)

In [ ]:
credit_cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Card_ID          557 non-null    int64
 1   Customer_ID      557 non-null    int64
 2   Account_ID       557 non-null    int64
 3   Branch           557 non-null    object
 4   Card_Number      557 non-null    int64
 5   Card_Type        557 non-null    object
 6   Card_Network     557 non-null    object
 7   Credit_Limit     557 non-null    int64
 8   Current_Balance  557 non-null    float64
 9   Issued_Date      557 non-null    object
 10  Expiry_Date      557 non-null    object
 11  Status           557 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 52.3+ KB

In [ ]:
credit_cards['Customer_ID'] = credit_cards['Customer_ID'].astype(str)

In [ ]:
credit_cards['Card_Number'] = credit_cards['Card_Number'].astype(str)

In [ ]:
credit_cards['Issued_Date'] = pd.to_datetime(credit_cards['Issued_Date'])

In [ ]:
credit_cards['Expiry_Date'] = pd.to_datetime(credit_cards['Expiry_Date'])

In [ ]:
print(credit_cards.dtypes)

Card_ID                     int64
Customer_ID                object
Account_ID                  int64
Branch                     object
Card_Number                object
Card_Type                  object
Card_Network               object
Credit_Limit                int64
Current_Balance           float64
Issued_Date        datetime64[ns]
Expiry_Date        datetime64[ns]
Status                     object
dtype: object

##### Branches

In [ ]:
branches.head()

,Branch_ID,Branch_Name,City,Manager_Name,Total_Employees,Branch_Revenue,Opening_Date,Performance_Rating
0,1,"Wang, Mcdonald and Church Branch",Kellitown,Kevin Jones,141,16849288.09,2008-08-01,2
1,2,Crawford-Torres Branch,Angelaburgh,Andrea Steele,39,5822279.32,2015-09-17,1
2,3,Bridges Inc Branch,Johnsonfort,Michael Coleman,195,2114594.03,2012-07-30,3
3,4,Garcia Group Branch,New Kyleberg,Dawn Cooper,144,3390389.63,2018-06-27,2
4,5,"Arroyo, Moore and Freeman Branch",West Coryborough,Samantha Kennedy,42,2771910.11,2012-01-04,5

In [ ]:
branches.isnull().sum()

Branch_ID             0
Branch_Name           0
City                  0
Manager_Name          0
Total_Employees       0
Branch_Revenue        0
Opening_Date          0
Performance_Rating    0
dtype: int64

In [ ]:
branches.duplicated().sum()

np.int64(0)

In [ ]:
branches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Branch_ID           520 non-null    int64
 1   Branch_Name         520 non-null    object
 2   City                520 non-null    object
 3   Manager_Name        520 non-null    object
 4   Total_Employees     520 non-null    int64
 5   Branch_Revenue      520 non-null    float64
 6   Opening_Date        520 non-null    object
 7   Performance_Rating  520 non-null    int64
dtypes: float64(1), int64(3), object(4)
memory usage: 32.6+ KB

In [ ]:
branches['Opening_Date'] = pd.to_datetime(branches['Opening_Date'])

In [ ]:
print(branches.dtypes)

Branch_ID                      int64
Branch_Name                   object
City                          object
Manager_Name                  object
Total_Employees                int64
Branch_Revenue               float64
Opening_Date          datetime64[ns]
Performance_Rating             int64
dtype: object

##### Support_Tickets

In [ ]:
support_tickets.head()

,Ticket_ID,Customer_ID,Account_ID,Loan_ID,Branch_Name,Issue_Category,Description,Date_Opened,Date_Closed,Priority,Status,Resolution_Remarks,Support_Agent,Channel,Customer_Rating
0,T00001,C0478,A1825,NaN,Gonzalez-Martin Branch,Loan Payment Delay,Client raised loan payment delay.,2017-09-30,2017-10-24,Low,Closed,Card replaced and activated.,Leena Apte,Email,1
1,T00002,C0443,A3583,NaN,Baldwin and Sons Branch,Loan Foreclosure,Client raised loan foreclosure.,2015-04-19,2015-05-12,Critical,In Progress,Card replaced and activated.,Owen Mahajan,In-person,1
2,T00003,C0057,A2616,442.0,"Porter, Osborne and Mendez Branch",Interest Rate Dispute,Customer reported interest rate dispute.,2016-09-28,2016-10-23,High,Resolved,Loan schedule updated.,Wishi Chhabra,Email,4
3,T00004,C0301,A8786,NaN,"Stafford, Oneal and Williams Branch",Mismatch in Account Statement,Client raised mismatch in account statement.,2019-03-31,2019-04-10,High,Closed,Pending customer verification.,Gabriel Mutti,Email,1
4,T00005,C0238,A3734,NaN,Evans-Mercado Branch,KYC Update Required,System detected kyc update required.,2017-08-11,NaN,Critical,Resolved,Pending customer verification.,Ekani Oza,In-person,2

In [ ]:
support_tickets.duplicated().sum()

np.int64(0)

In [ ]:
support_tickets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ticket_ID           600 non-null    object
 1   Customer_ID         600 non-null    object
 2   Account_ID          600 non-null    object
 3   Loan_ID             229 non-null    float64
 4   Branch_Name         600 non-null    object
 5   Issue_Category      600 non-null    object
 6   Description         600 non-null    object
 7   Date_Opened         600 non-null    object
 8   Date_Closed         496 non-null    object
 9   Priority            600 non-null    object
 10  Status              600 non-null    object
 11  Resolution_Remarks  600 non-null    object
 12  Support_Agent       600 non-null    object
 13  Channel             600 non-null    object
 14  Customer_Rating     600 non-null    int64
dtypes: float64(1), int64(1), object(13)
memory usage: 70.4+ KB

In [ ]:
support_tickets['Loan_ID'] = support_tickets['Loan_ID'].astype(str)

In [ ]:
support_tickets['Date_Opened'] = pd.to_datetime(support_tickets['Date_Opened'])

In [ ]:
support_tickets['Date_Closed'] = pd.to_datetime(support_tickets['Date_Closed'])

In [ ]:
support_tickets.isnull().sum()

Ticket_ID               0
Customer_ID             0
Account_ID              0
Loan_ID                 0
Branch_Name             0
Issue_Category          0
Description             0
Date_Opened             0
Date_Closed           104
Priority                0
Status                  0
Resolution_Remarks      0
Support_Agent           0
Channel                 0
Customer_Rating         0
dtype: int64

In [ ]:
support_tickets['Loan_ID'] = support_tickets['Loan_ID'].replace(
    ['nan', 'NaN', 'None', ''], np.nan
)

In [ ]:
support_tickets['Loan_ID'] = support_tickets['Loan_ID'].astype('string')

In [ ]:
support_tickets['Date_Closed'] = pd.to_datetime(
    support_tickets['Date_Closed'], errors='coerce'
)

In [ ]:
#-------------------------------------------
# step 3 : connect to mysql
#-------------------------------------------

In [ ]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Aarthiba@123"
)
cursor = conn.cursor()

#### create database

In [ ]:
cursor.execute("CREATE DATABASE IF NOT EXISTS banksight")
cursor.execute("USE banksight")
print("Database selected")

Database selected

In [ ]:
#-------------------------------------------
# step 4 : create tables
#-------------------------------------------

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS customers (
    customer_id VARCHAR(10) PRIMARY KEY,
    name VARCHAR(50),
    gender CHAR(1),
    age INT,
    city VARCHAR(50),
    account_type VARCHAR(20),
    join_date DATE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS accounts (
    customer_id VARCHAR(10),
    account_balance DECIMAL(12,2),
    last_updated DATETIME,
               
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
    ON DELETE CASCADE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS transactions (
    txn_id VARCHAR(10) PRIMARY KEY,
    customer_id VARCHAR(10),
    txn_type VARCHAR(50),
    amount DECIMAL(12,2),
    txn_time DATETIME,
    status VARCHAR(50),
               
    FOREIGN KEY (customer_id) 
    REFERENCES customers(customer_id)
    ON DELETE CASCADE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS loans (
    loan_id INT PRIMARY KEY,
    customer_id VARCHAR(10),
    account_id INT,
    branch VARCHAR(50),
    loan_type VARCHAR(50),
    loan_amount INT,
    interest_rate DECIMAL(12,2),
    loan_term_months INT,
    start_date DATE,
    end_date DATE,
    loan_status VARCHAR(50),
               
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
    ON DELETE CASCADE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS credit_cards (
    card_id INT PRIMARY KEY,
    customer_id VARCHAR(10),
    account_id INT,
    branch VARCHAR(50),
    card_number VARCHAR(20),
    card_type VARCHAR(50),
    card_network VARCHAR(50),
    credit_limit INT,
    current_balance DECIMAL(12,2),
    issued_date DATE,
    expiry_date DATE,
    status VARCHAR(50),
               
    FOREIGN KEY (customer_id) 
    REFERENCES customers( customer_id)
    ON DELETE CASCADE
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS branches (
    branch_id INT PRIMARY KEY,
    branch_name VARCHAR(50),
    city VARCHAR(50),
    manager_name VARCHAR(50),
    total_employees int,
    branch_revenue DECIMAL(12,2),
    opening_date DATE,
    performance_rating int
)
""")

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS support_tickets (
    ticket_id VARCHAR(10) PRIMARY KEY,
    customer_id VARCHAR(10),
    account_id VARCHAR(10),
    loan_id VARCHAR(50) NULL,
    branch_name VARCHAR(50),
    issue_category VARCHAR(50),
    description  TEXT,
    date_opened DATE,
    date_closed DATE,
    priority VARCHAR(50),
    status VARCHAR(50),
    resolution_remarks TEXT,
    support_agent VARCHAR(50),
    channel VARCHAR(50),
    customer_rating int,
               
    FOREIGN KEY (customer_id) 
    REFERENCES customers(customer_id)
    ON DELETE CASCADE
)
""")

#### insert rows

In [ ]:
cursor.execute("DELETE FROM customers")
conn.commit()

IntegrityError: 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`banksight`.`accounts`, CONSTRAINT `accounts_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`))

In [ ]:
for _, row in customers.iterrows():
    cursor.execute("""
        INSERT INTO customers (customer_id, name, gender, age, city, account_type, join_date)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
    """, (row['customer_id'], 
          row['name'], 
          row['gender'], 
          row['age'], 
          row['city'], 
          row['account_type'], 
          row['join_date']))

conn.commit()

IntegrityError: 1062 (23000): Duplicate entry 'C0001' for key 'customers.PRIMARY'

In [ ]:
for _, row in accounts.iterrows():
    cursor.execute("""
        INSERT INTO accounts (customer_id, account_balance,last_updated)
        VALUES (%s, %s,%s)
    """, (row['customer_id'], 
          row['account_balance'],
          row['last_updated']))

conn.commit()

IntegrityError: 1062 (23000): Duplicate entry 'C0001' for key 'accounts.PRIMARY'

In [ ]:
for _, row in transactions.iterrows():
    cursor.execute("""
        INSERT INTO transactions (txn_id, customer_id, txn_type, amount, txn_time, status)
        VALUES (%s, %s, %s, %s, %s, %s)
    """, (row['txn_id'], 
          row['customer_id'],
          row['txn_type'],
          row['amount'],
          row['txn_time'],
          row['status'],))

conn.commit()

IntegrityError: 1062 (23000): Duplicate entry 'T00001' for key 'transactions.PRIMARY'

In [ ]:
for _, row in loans.iterrows():
    cursor.execute("""
        INSERT INTO loans (loan_id, customer_id, account_id, branch, loan_type, loan_amount, interest_rate, loan_term_months, start_date, end_date, loan_status)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (row['Loan_ID'], 
          row['Customer_ID'],
          row['Account_ID'],
          row['Branch'],
          row['Loan_Type'],
          row['Loan_Amount'],
          row['Interest_Rate'],
          row['Loan_Term_Months'],
          row['Start_Date'],
          row['End_Date'],
          row['Loan_Status']))

conn.commit()

IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`banksight`.`loans`, CONSTRAINT `loans_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`))

In [ ]:
for _, row in accounts.iterrows():
    cursor.execute("""
        INSERT INTO accounts (customer_id, account_balance,last_updated)
        VALUES (%s, %s,%s)
    """, (row['customer_id'], 
          row['account_balance'],
          row['last_updated']))

conn.commit()

IntegrityError: 1062 (23000): Duplicate entry 'C0001' for key 'accounts.PRIMARY'

In [ ]:
for _, row in transactions.iterrows():
    cursor.execute("""
        INSERT INTO transactions (txn_id, customer_id, txn_type, amount, txn_time, status)
        VALUES (%s, %s, %s, %s, %s, %s)
    """, (row['txn_id'], 
          row['customer_id'],
          row['txn_type'],
          row['amount'],
          row['txn_time'],
          row['status'],))

conn.commit()

IntegrityError: 1062 (23000): Duplicate entry 'T00001' for key 'transactions.PRIMARY'

In [ ]:
for _, row in loans.iterrows():
    cursor.execute("""
        INSERT INTO loans (loan_id, customer_id, account_id, branch, loan_type, loan_amount, interest_rate, loan_term_months, start_date, end_date, loan_status)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (row['Loan_ID'], 
          row['Customer_ID'],
          row['Account_ID'],
          row['Branch'],
          row['Loan_Type'],
          row['Loan_Amount'],
          row['Interest_Rate'],
          row['Loan_Term_Months'],
          row['Start_Date'],
          row['End_Date'],
          row['Loan_Status']))

conn.commit()

IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`banksight`.`loans`, CONSTRAINT `loans_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`))